INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('01','ACOSTA');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('02','AGUASAY');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('03','BOLIVAR');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('04','CARIPE');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('05','CEDEÑO');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('06','EZEQUIEL ZAMORA');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('07','LIBERTADOR');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('08','MATURIN');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('09','PIAR');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('10','PUNCERES');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('11','SANTA BARBARA');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('12','SOTILLO');
INSERT INTO municipios (codigo_municipio,nombre_municipio) VALUES ('13','URACOA');

INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('01','001', 'SAN ANTONIO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('01','002', 'SAN FRANCISCO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('02','003', 'AGUASAY');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('03','004', 'CARIPITO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','005', 'EL GUÁCHARO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','006', 'LA GUANOTA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','007', 'SABANA DE PIERDRA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','008', 'SAN AGUSTIN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','009', 'TERESEN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('04','010', 'CARIPE');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('05','011', 'AREO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('05','012', 'CAPITAL CEDEÑO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('05','013', 'SAN FELIX DE CANTALICIO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('05','014', 'VIENTO FRESCO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('06','015', 'EL TEJERO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('06','016', 'PUNTA DE MATA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('07','017', 'CHAGUARAMAS');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('07','018', 'LAS ALHUACAS');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('07','019', 'TABASCA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('07','020', 'TEMBLADOR');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','021', 'ALTO DE LOS GODOS');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','022', 'BOQUERÓN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','023', 'LAS COCUIZAS');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','024', 'LA CRUZ');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','025', 'SAN SIMÓN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','026', 'EL COROZO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','027', 'EL FURRIAL');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','028', 'JUSEPÍN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','029', 'LA PICA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('08','030', 'SAN VICENTE');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','031', 'APARICIO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','032', 'ARAGUA DE MATURIN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','033', 'CHAGUARAMAL');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','034', 'EL PINTO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','035', 'GUANAGUANA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','036', 'LA TOSCANA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('09','037', 'TAGUAYA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('10','038', 'CACHIPO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('10','039', 'QUIRIQUIRE');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('11','040', 'SANTA BÁRBARA');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('11','041', 'MORÓN');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('12','042', 'BARRANCAS');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('12','043', 'LOS BARRANCOS DE FAJARDO');
INSERT INTO parroquias (fk_codigo_municipio,codigo_parroquia, nombre_parroquia) VALUES ('13','044', 'URACOA');